ARG PTH_VERSION=1.9.0-cuda11.1-cudnn8

# 1/Building apex with pytorch:*-devel
FROM pytorch/pytorch:${PTH_VERSION}-devel AS apex-builder

ARG ARG_TORCH_CUDA_ARCH_LIST="3.5 5.2 6.0 6.1 7.0+PTX 8.0"
ENV TORCH_CUDA_ARCH_LIST=$ARG_TORCH_CUDA_ARCH_LIST

# Install git
RUN apt-get update && apt-get install -y --no-install-recommends git && \
     rm -rf /var/lib/apt/lists/*

# Build apex
RUN echo "Setup NVIDIA Apex" && \
    tmp_apex_path="/tmp/apex" && \
    rm -rf $tmp_apex_path && \
    git clone https://github.com/NVIDIA/apex $tmp_apex_path && \
    cd $tmp_apex_path && \
    pip wheel --no-cache-dir --global-option="--cpp_ext" --global-option="--cuda_ext" .

# Build runtime image
FROM pytorch/pytorch:${PTH_VERSION}-runtime

# Apex
COPY --from=apex-builder /tmp/apex/apex-*.whl /tmp/apex/
RUN pip install --no-cache-dir /tmp/apex/apex-*.whl && \
    rm -fr /tmp/apex

WORKDIR /workspace

COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
RUN pip install torchelastic

RUN apt-get -q update && apt-get -q install -y wget unzip
COPY install_etcd install_etcd
RUN chmod -R u+x install_etcd
RUN mkdir -p bin
RUN ./install_etcd -d bin
ENV PATH=/workspace/bin:${PATH}


COPY src src

ENV PYTHONPATH "${PYTHONPATH}:/workspace"

ENTRYPOINT ["python", "-m", "torch.distributed.run", "--nproc_per_node=1", "src/train_lm.py", "--cuda", "--fp16", "--group-by-size", "-bs", "3", "--elastic"]
CMD ["--help"]





