ARG PTH_VERSION=1.9.0-cuda11.1-cudnn8
# Build runtime image
FROM pytorch/pytorch:${PTH_VERSION}-runtime

WORKDIR /workspace

COPY requirements.txt ./requirements.txt
RUN pip install -r requirements.txt
RUN pip install torchelastic
COPY src src

ENV PYTHONPATH "${PYTHONPATH}:/workspace"
ENTRYPOINT ["python", "src/train_lm.py"]
CMD ["--help"]



